export default { path: '/shapes/pear/', en: {
  meta: { title: 'Pear Body Shape (Triangle and Spoon): Rules, Boundaries and Names', description: 'Pear is the everyday name for two FFIT shapes: Triangle, where the hips are at least 3.6 inches wider than the bust, and Spoon, where the high hip flares. The exact rules, the fourth measurement that separates them, and where rectangle and hourglass begin.' },
  layout: { eyebrow: 'Shapes · Pear', h1: 'Pear body shape', lead: 'Pear is not a rule; it is the everyday name for a family of shapes in which the hips are clearly wider than the bust. Under the FFIT rules this site runs, that family is Triangle and Spoon, with Bottom Hourglass sitting on its edge. The three differ in how defined the waist is and in one measurement most people have never taken. This page sets out the rules in numbers and where the neighbouring shapes begin.', ctaHead: 'See which of the three you are', ctaNote: 'The calculator asks for the high hip only if your first three numbers need it. Nothing is uploaded.', updated: '2026-09-15' },
  tableData: { head: 'The pear family', cols: ['FFIT shape', 'Rule (inches)', 'What separates it'], rows: [
    ['Triangle', 'hips − bust ≥ 3.6; and 0 ≤ hips − waist < 9 (or bust − waist < 0 with hips ≥ waist)', 'Hips clearly wider than bust, waist not strongly defined'],
    ['Spoon', 'hips − bust > 2; hips − waist ≥ 7; high hip ÷ waist ≥ 1.193', 'Waist defined and the high hip flares out above it'],
    ['Bottom hourglass', '3.6 ≤ hips − bust < 10; hips − waist ≥ 9; high hip ÷ waist < 1.193', 'Waist strongly defined, high hip does not flare — classed with hourglass'],
  ] },
  blocks: [
    { t: 'h2', s: 'What “pear” means in numbers' },
    { t: 'p', s: 'The shared feature is hips minus bust: 3.6 inches (9.1 cm) or more for Triangle, more than 2 inches for Spoon. Everything else is about the waist. Triangle has hips minus waist under 9 inches, so the waist is not sharply defined relative to the hips. Spoon has hips minus waist of 7 or more and, critically, a high hip that flares: high hip divided by waist of 1.193 or more. Bottom Hourglass has the strongest waist definition, 9 inches or more below the hips, and a high hip that does not flare; FFIT groups it with the hourglass family, though in everyday terms it is a pear with a very defined waist.' },
    { t: 'table' },
    { t: 'h2', s: 'The measurement that decides Spoon versus the others' },
    { t: 'p', s: 'High hip is the circumference about 7 cm (3 inches) below the waist, roughly at the top of the hip bones. It is the one FFIT measurement most people have never taken, and it is the only thing that separates Spoon from Bottom Hourglass, and in many cases from Triangle. The preconditions are wide — hips more than 2 inches over bust, waist 7 or more under hips — so a large share of women land in the zone where it is needed. In the ANSUR II sample, 34.7% of women did. The calculator asks for it only when your first three numbers require it; without it, the honest result is “one of Spoon, Bottom Hourglass, Triangle or Rectangle”, which is not much of a result.' },
    { t: 'h2', s: 'Where rectangle and hourglass begin' },
    { t: 'p', s: 'Rectangle begins where hips minus bust drops below 3.6 inches. That is the single most crowded boundary in the whole system: in the ANSUR II test the largest group of women near any boundary sat here, and the bust measurement was the one that most often decided it. If you measured the bust over a padded bra, or with the tape dropping at the back, the difference can move by enough to change the label.' },
    { t: 'p', s: 'Hourglass begins when the hips come back within 3.6 inches of the bust while the waist stays defined. Bottom Hourglass, as above, is the pear-shaped body whose waist is 9 or more inches below the hips and whose high hip does not flare; it is the pear family’s exit into the hourglass family.' },
    { t: 'h2', s: 'Names' },
    { t: 'p', s: 'Pear and triangle mean the same thing in nearly all systems. Spoon is FFIT’s own term and is rarely used elsewhere; some styling guides call it a bottom-heavy hourglass or a curvy pear. A-shape is another synonym for triangle. None of these carries a different rule; they are the same relationship of hips to bust under different names.' },
    { t: 'h2', s: 'What the label does not mean' },
    { t: 'p', s: 'Only that the hips measure wider than the bust by a stated margin. It says nothing about height, weight, where on the hips the width sits, or leg length. The styling page for this family describes what tends to balance a wider lower body if that is what you want; wanting it is a preference, not a requirement.' },
    { t: 'ul', items: [
      'Styling direction: <a href="/shapes/pear/outfits/">pear outfits</a>',
      'On the boundary: <a href="/pear-vs-rectangle/">pear vs rectangle</a> · <a href="/hourglass-vs-pear/">hourglass vs pear</a>',
      'Where the high hip is measured: <a href="/how-to-measure/">how to measure</a>',
    ] },
  ],
  faq: [
    ['What is the difference between pear and triangle?', 'None. Triangle is the FFIT name and pear the everyday one, for hips at least 3.6 inches wider than the bust without a strongly defined waist.'],
    ['What is a spoon body shape?', 'A pear-family shape where the waist is defined (hips at least 7 inches larger than waist) and the high hip flares out above the waist: high hip ÷ waist ≥ 1.193. It needs the high-hip measurement to identify.'],
    ['Is bottom hourglass a pear?', 'In everyday terms yes — the hips are 3.6 inches or more wider than the bust. FFIT files it under hourglass because the waist is at least 9 inches smaller than the hips. The calculator reports the FFIT name and the family it maps to.'],
    ['My hips are wider but the result says rectangle. Why?', 'Because the difference is under 3.6 inches (9.1 cm). This is the most crowded boundary in the system; the calculator shows how many centimetres you are from it, and the bust measurement is usually the one to re-check.'],
    ['Do I have to measure my high hip?', 'Only if the calculator asks, which it does when your first three numbers fall where Spoon and Bottom Hourglass overlap. Otherwise three measurements are enough.'],
  ],
} };
